# Generated by Django 6.0.5 on 2026-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('comments', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_address2', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=100)),
                ('agree', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('birth_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('favorite_color', models.CharField(max_length=20)),
                ('favorite_colour', models.CharField(max_length=20)),
                ('favorite_colors', models.CharField(max_length=100)),
            ],
        ),
    ]
